#!/usr/bin/env python3
"""
sync_copyparty.py — regenerate copyparty.conf from the users table.

The users table is the single identity authority. Each user's copyparty
password is their file_token (random service credential). Volumes are
generated per user: staging-backed upload vols + browse vols, plus the
shared/public/staging/drop layout. Then copyparty is reloaded.

Run after any user change:  python3 sync_copyparty.py
"""
import os, sys, subprocess

sys.path.insert(0, os.path.dirname(__file__))
import db

CONF = os.environ.get("PC_CPCONF", "/opt/copyparty/config/copyparty.conf")

HEADER = """# GENERATED by server/sync_copyparty.py — do not hand-edit accounts/volumes.
# Identity source of truth: the users table in the platform DB.
[global]
  p: 3923
  e2dsa
  e2ts
"""

PUBLIC_CATS = ["movies", "tv", "music", "photos", "books", "audiobooks", "podcasts"]


def generate():
    conn = db.connect()
    users = conn.execute(
        "SELECT username, file_token, is_admin FROM users WHERE disabled=0 "
        "ORDER BY username").fetchall()
    grps = conn.execute(
        "SELECT gr.id, gr.name FROM groups gr").fetchall()
    gmembers = {gr["id"]: [r["username"] for r in conn.execute(
        "SELECT u.username FROM group_members gm JOIN users u ON u.id=gm.user_id "
        "WHERE gm.group_id=? AND u.disabled=0", (gr["id"],)).fetchall()] for gr in grps}
    conn.close()
    if not users:
        raise SystemExit("no users in DB; run app.py --init-admin first")

    admins = [u["username"] for u in users if u["is_admin"]]
    members = [u["username"] for u in users if not u["is_admin"]]
    out = [HEADER, "[accounts]"]
    for u in users:
        out.append(f"  {u['username']}: {u['file_token']}")
    out.append("")

    def admin_lines(perm="rwmda"):
        return [f"    {perm}: {a}" for a in admins]

    # browse vaults (read/move/delete; uploads go via /up)
    for u in users:
        out += [f"[/vault/{u['username']}]", f"  /users/{u['username']}/private",
                "  accs:", f"    rmd: {u['username']}"] + admin_lines() + [""]

    # public browse
    for cat in PUBLIC_CATS:
        out += [f"[/public/{cat}]", f"  /storage/pool/{cat}", "  accs:",
                "    r: *"] + admin_lines() + [""]

    # staging-backed upload vols
    for u in users:
        out += [f"[/up/vault/{u['username']}]", f"  /staging/vault/{u['username']}",
                "  accs:", f"    w: {u['username']}"] + admin_lines() + [""]
    for cat in PUBLIC_CATS:
        out += [f"[/up/public/{cat}]", f"  /staging/public/{cat}", "  accs:"]
        out += [f"    w: {u['username']}" for u in users] + admin_lines() + [""]

    # group shared spaces: members read/manage, uploads via staging twin
    for gr in grps:
        slug = gr["name"].lower().replace(" ", "-")
        mem = gmembers.get(gr["id"], [])
        out += [f"[/group/{slug}]", f"  /groups/{slug}", "  accs:"]
        out += [f"    rmd: {m}" for m in mem] + admin_lines() + [""]
        out += [f"[/up/group/{slug}]", f"  /staging/group/{slug}", "  accs:"]
        out += [f"    w: {m}" for m in mem] + admin_lines() + [""]

    # admin staging window + anonymous drop
    out += ["[/staging]", "  /staging", "  accs:"] + admin_lines() + [""]
    out += ["[/drop]", "  /staging/public/unknown", "  accs:", "    w: *"] + admin_lines() + [""]
    return "\n".join(out)


# copyparty runs as its own unprivileged user. Anything this script creates
# while running as root is root-owned by default -> copyparty gets no write bit
# and every upload into that volume 403s. Always hand ownership over.
CP_USER = os.environ.get("PC_CP_USER", "copyparty")


def _cp_ids():
    try:
        import pwd, grp
        return pwd.getpwnam(CP_USER).pw_uid, grp.getgrnam(CP_USER).gr_gid
    except Exception:
        return None, None


def _own(path):
    """chown path to copyparty:copyparty (no-op when not root)."""
    uid, gid = _cp_ids()
    if uid is None or os.geteuid() != 0:
        return
    try:
        os.chown(path, uid, gid)
        os.chmod(path, 0o775)
    except OSError:
        pass


def _mkdir(path):
    os.makedirs(path, exist_ok=True)
    _own(path)


def fix_perms():
    """Repair ownership of every managed tree (root only). Idempotent."""
    uid, gid = _cp_ids()
    if uid is None:
        print(f"! no such user '{CP_USER}' — skipping perms repair")
        return
    if os.geteuid() != 0:
        print("! not root — cannot repair ownership")
        return
    fixed = 0
    for root in ("/staging", "/groups", "/users", "/storage/pool"):
        if not os.path.isdir(root):
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            for p in [dirpath] + [os.path.join(dirpath, f) for f in filenames]:
                try:
                    st = os.stat(p)
                    if st.st_uid != uid or st.st_gid != gid:
                        os.chown(p, uid, gid)
                        fixed += 1
                except OSError:
                    pass
    print(f"perms: reassigned {fixed} paths to {CP_USER}:{CP_USER}")


def ensure_dirs():
    conn = db.connect()
    users = conn.execute("SELECT username FROM users WHERE disabled=0").fetchall()
    grps = conn.execute("SELECT name FROM groups").fetchall()
    conn.close()
    for base in ("/staging", "/staging/vault", "/staging/group", "/staging/public",
                 "/groups", "/users", "/storage/pool"):
        _mkdir(base)
    for gr in grps:
        slug = gr["name"].lower().replace(" ", "-")
        _mkdir(f"/groups/{slug}")
        _mkdir(f"/staging/group/{slug}")
    for u in users:
        _mkdir(f"/users/{u['username']}")
        _mkdir(f"/users/{u['username']}/private")
        _mkdir(f"/staging/vault/{u['username']}")
    for cat in PUBLIC_CATS + ["unknown"]:
        _mkdir(f"/staging/public/{cat}")
        if cat != "unknown":
            _mkdir(f"/storage/pool/{cat}")


def main():
    if "--fix-perms" in sys.argv:
        fix_perms()
        return
    conf = generate()
    ensure_dirs()
    with open(CONF, "w") as f:
        f.write(conf)
    os.chmod(CONF, 0o600)
    try:
        subprocess.run(["sudo", "-n", "systemctl", "reload-or-restart", "copyparty"],
                       check=True, capture_output=True, timeout=30)
        print("copyparty.conf regenerated + copyparty reloaded")
    except Exception as e:
        print(f"conf written; reload copyparty manually ({e})")


if __name__ == "__main__":
    main()
