#!/usr/bin/env python3
"""
sync_copyparty.py — regenerate copyparty.conf from the users table.

The users table is the single identity authority. Each user's copyparty
password is their file_token (random service credential). Volumes are
generated per user: staging-backed upload vols + browse vols, plus the
shared/public/staging/drop layout. Then copyparty is reloaded.

Run after any user change:  python3 sync_copyparty.py
"""
import os, sys, subprocess

sys.path.insert(0, os.path.dirname(__file__))
import db

CONF = os.environ.get("PC_CPCONF", "/opt/copyparty/config/copyparty.conf")

HEADER = """# GENERATED by server/sync_copyparty.py — do not hand-edit accounts/volumes.
# Identity source of truth: the users table in the platform DB.
[global]
  p: 3923
  e2dsa
  e2ts
"""

PUBLIC_CATS = ["movies", "tv", "music", "photos"]


def generate():
    conn = db.connect()
    users = conn.execute(
        "SELECT username, file_token, is_admin FROM users WHERE disabled=0 "
        "ORDER BY username").fetchall()
    grps = conn.execute(
        "SELECT gr.id, gr.name FROM groups gr").fetchall()
    gmembers = {gr["id"]: [r["username"] for r in conn.execute(
        "SELECT u.username FROM group_members gm JOIN users u ON u.id=gm.user_id "
        "WHERE gm.group_id=? AND u.disabled=0", (gr["id"],)).fetchall()] for gr in grps}
    conn.close()
    if not users:
        raise SystemExit("no users in DB; run app.py --init-admin first")

    admins = [u["username"] for u in users if u["is_admin"]]
    members = [u["username"] for u in users if not u["is_admin"]]
    out = [HEADER, "[accounts]"]
    for u in users:
        out.append(f"  {u['username']}: {u['file_token']}")
    out.append("")

    def admin_lines(perm="rwmda"):
        return [f"    {perm}: {a}" for a in admins]

    # browse vaults (read/move/delete; uploads go via /up)
    for u in users:
        out += [f"[/vault/{u['username']}]", f"  /users/{u['username']}/private",
                "  accs:", f"    rmd: {u['username']}"] + admin_lines() + [""]

    # public browse
    for cat in PUBLIC_CATS:
        out += [f"[/public/{cat}]", f"  /storage/pool/{cat}", "  accs:",
                "    r: *"] + admin_lines() + [""]

    # staging-backed upload vols
    for u in users:
        out += [f"[/up/vault/{u['username']}]", f"  /staging/vault/{u['username']}",
                "  accs:", f"    w: {u['username']}"] + admin_lines() + [""]
    for cat in PUBLIC_CATS:
        out += [f"[/up/public/{cat}]", f"  /staging/public/{cat}", "  accs:"]
        out += [f"    w: {u['username']}" for u in users] + admin_lines() + [""]

    # group shared spaces: members read/manage, uploads via staging twin
    for gr in grps:
        slug = gr["name"].lower().replace(" ", "-")
        mem = gmembers.get(gr["id"], [])
        out += [f"[/group/{slug}]", f"  /groups/{slug}", "  accs:"]
        out += [f"    rmd: {m}" for m in mem] + admin_lines() + [""]
        out += [f"[/up/group/{slug}]", f"  /staging/group/{slug}", "  accs:"]
        out += [f"    w: {m}" for m in mem] + admin_lines() + [""]

    # admin staging window + anonymous drop
    out += ["[/staging]", "  /staging", "  accs:"] + admin_lines() + [""]
    out += ["[/drop]", "  /staging/public/unknown", "  accs:", "    w: *"] + admin_lines() + [""]
    return "\n".join(out)


def ensure_dirs():
    conn = db.connect()
    users = conn.execute("SELECT username FROM users WHERE disabled=0").fetchall()
    grps = conn.execute("SELECT name FROM groups").fetchall()
    conn.close()
    for gr in grps:
        slug = gr["name"].lower().replace(" ", "-")
        os.makedirs(f"/groups/{slug}", exist_ok=True)
        os.makedirs(f"/staging/group/{slug}", exist_ok=True)
    for u in users:
        for p in (f"/users/{u['username']}/private", f"/staging/vault/{u['username']}"):
            os.makedirs(p, exist_ok=True)
    for cat in PUBLIC_CATS + ["unknown"]:
        os.makedirs(f"/staging/public/{cat}", exist_ok=True)
        if cat != "unknown":
            os.makedirs(f"/storage/pool/{cat}", exist_ok=True)


def main():
    conf = generate()
    ensure_dirs()
    with open(CONF, "w") as f:
        f.write(conf)
    os.chmod(CONF, 0o600)
    try:
        subprocess.run(["systemctl", "reload-or-restart", "copyparty"],
                       check=True, capture_output=True, timeout=30)
        print("copyparty.conf regenerated + copyparty reloaded")
    except Exception as e:
        print(f"conf written; reload copyparty manually ({e})")


if __name__ == "__main__":
    main()
